apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ljPAdcWF1nbU1GRKlUdEJjseG6g=,iv:sUTipV/WiCKQEptDUQlEi3DC48/E23r55pX4edRamg8=,tag:AY25fO29QJ9jHxTKmLWsGA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:QFiKMZbpI+QhMFkuIWjZ/73HBHCzFDVx9hIAIao99f5cEYvI1Q==,iv:KzKz3A0lDmFg7eg4ksj5h9PJMK/irLLP2dp6RxaUQ24=,tag:XvDICOKmGqA5nKDNv3ailw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:uPJMaj/TEPPCfNFV8vNV,iv:4/7UXyLYX7KetWVnmZnq8C70slFjDTc3+YztoZ9OvNs=,tag:msFFXN2ydgvrdvvFpxRQ0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZTJSQjFRV2E5QWpadG4w
            ci9kN1ZtWG5pcWtXU1hjUzBna05VMmZvcUJjClYyNHFQVmhpYVR2TWpyQVl5RWlN
            N2cwbVhEOGZxWTFDeFJkdFVBRElWYjQKLS0tIFBQcUc2cWhlc2VmbHJWUjlKWUNX
            a2V1QjFJUCtEd1JaRnhacHh6NnBmRWcKtFikeqgQYikX1pREx+2kGc0K3lluAe4f
            qPY30rAtOzJYqYWN04MbLQK4N1VyOsPJPEu/vSGs6fsnFUw2WtU77Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T09:49:08Z"
    mac: ENC[AES256_GCM,data:YH3kbLi4Uf/DLBpgzhYcaakljg15NytePvgAXIKrzQNc9Or9f6Eh/6ECLTSL+ycVVctaFMhehjmTD5UGcjx6lADQC9XxzxnmcWBebIM68jRO+t8VvVqinSM+V+jHdrlPuNr9lCkqDE23LE3N5515UrmwStwud12e4kYZUOO1EUY=,iv:FKofKDQgvxrlnLTZBu8pNVx1OfMsICnpIrdUMIYwjT8=,tag:lqbY3xeMaxHRSgu/2qgRxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
