---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1japzvh40ygfy2vfdxznvledx3ysna4xkwe4hs4mldf8cg926asrqnackfa
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1japzvh40ygfy2vfdxznvledx3ysna4xkwe4hs4mldf8cg926asrqnackfa
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1japzvh40ygfy2vfdxznvledx3ysna4xkwe4hs4mldf8cg926asrqnackfa
