---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
