---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1vk5rlpzjs7ajajr6pp768hh4e379y73t7gk7469wcjcfrkhe35ls8y29sh
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vk5rlpzjs7ajajr6pp768hh4e379y73t7gk7469wcjcfrkhe35ls8y29sh
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vk5rlpzjs7ajajr6pp768hh4e379y73t7gk7469wcjcfrkhe35ls8y29sh
