apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:T2q2T68PUKaUu8J8YrhBHbkXZSUwaLVVaD+LT7DsqkKB2JsMKz2CPA==,iv:yxyS5WtTx9KvfHpDuMmd5WUnpezE9pT5hgE/n+Xh2SM=,tag:5e0dyenTz0ssdOMbzAw33w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vk5rlpzjs7ajajr6pp768hh4e379y73t7gk7469wcjcfrkhe35ls8y29sh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXckhMWUJDOHVvM3paTjJE
            LzR5UXRjVndtaGJEREF1WHB2VVZkTi9tczFnCjI2d2s2SFRsam16Z1lLb1RkZW9x
            d2RuN2VFTGNRdjlzbE1uRHIveG51Y2sKLS0tIC9Lb0tzS0lLTVJrTnZTZTJjWk01
            YlRaM1JDVCtNWE9xa29TZEhvUWpCTGsKILyRlBPIbpXTOzFMhvfo9FWIgUd+0gVQ
            FoQ9UdZyFo4lblRPokiNbjs+VHU5ECaxGLK+fjBaJb5fhRMH1DwxGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T14:15:02Z"
    mac: ENC[AES256_GCM,data:cKNgBk3i5pJBD493I3MhTmHFzcrogrJosHGJfG+7f2HBekpZpU94q6jjfXRltVS43ywfL2dwbWa7fNX5Sq86xismqQorQpJB9CREQbkPrjOVk7OdqdG5gvpwM65reB/mkk6x+liww8jRL/XVBypFQumpmf3kE0HMH//oj2C3ynU=,iv:pje4YQt8Me9IXcpzVfMdGKoqm22Wnz0sPkXfOT1K7PI=,tag:CCzPa+eSB8z0fRMLlkukVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
