apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:O9Ejlc/dQ4FeX6zRszP7VBbOo680oTZKr7tVKicDnQ9kF/Cr8g==,iv:4aX7cKsBbFadpnzUQ20Lgn0x7+9hypqeS3BzbQ9LqHk=,tag:QeJTXrmSg2PAZx2wpWJ5Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNjUraUt3b014UGthK3kw
            MTJzbWlBZTFva3lIMWVyVGxsQW1VK2Mxb1MwCmhhSmhLcmhyN0s2MEU5ckVKOS9T
            V3lRSDI2L0h5cTdHdU5SaUZBcjV4dTQKLS0tIGhUd1JlWkp1bmhqc3Nkek43WUpu
            RjRWcjllaVE4dGE5QllBcGFsSkJYOVkKnoMsnJKPif7NQUnKVfmyay5ELFjZ6MaM
            IYEKg7jrjkjRtODc/AbDpeVrnTFB5FUZ9UreAPm8gJoRS/sP9q1FKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T09:49:08Z"
    mac: ENC[AES256_GCM,data:b3SF242jJrHMKS5lAJJJ6OaKDLoxUMDfe3otb/keP3Y+yNW9XlG56WHeo3uw/AzHlNLHcdWQwWxC0LlP8IM6PMx0/ld2wcQv5AQOvzlCLqYQQ92CEcgAmnwkd7kNgtaFZcmmm6vTYEMRS8VWuFU4ydsSGoML5qg1v6NyV8VouCk=,iv:MFvVFhiNSGBcJ/jAga+N7rffDboX4SRbzBjfbJIt5R4=,tag:uPYob/0O4T3XyfrE9tuiVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
