apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:/Ei8FoK5DXc5FdYkEVV1ZzITk3uUphvLI1D7+qfiVKZ0uxyuqg==,iv:hxnNPDFRt7URGC9a5nHNvWPGy3Bh0Y7rF2xQzL60boQ=,tag:ziBSavsicQ692Hgkbg6fSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1japzvh40ygfy2vfdxznvledx3ysna4xkwe4hs4mldf8cg926asrqnackfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2JkZkc1Q0oxVGY1Wm9p
            eGE1aFBMMThlYVhySC9GdkR6bitpWjBmMHhVCjZaRE9YYTRNby9DclEzVkV2Z3Rh
            UzZib2lMWFpIYUZYdGRrVkh2ZVZEcjAKLS0tIG80Z3I4YzA4TU9sdnFlUENjVTRF
            Qk5EOTFnMk03WW1VSWNFdHkvS1FUS2sKh84y8PL1tNy2ef0HVrbdfpsQymMfIQD7
            oYMT6nOYvrnw0a5kUd25I+JutjaZu5uN/s1SeDw1290+SWcejLXpow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T11:40:10Z"
    mac: ENC[AES256_GCM,data:nArhyDGeiiWI+mmeDkF+6wO0vbXqsEKkVByWlp2+Dfu4dFaNxRngjHl8HWC3tur2EAzH4px6ZGMofItuJKa2D+pwv5yshNll2ePwTe06CedQ0hpSeMDGNSnefzQLwIiEvoVVMHYpfHl8OT7ufyz8H7cfX2CJsP4FNmw56tCMkaU=,iv:mo8jh838ZuIxxd1E29NS8bV6UzCxsDfSgfOiYDCs8EI=,tag:wQB+13xMz3VS0kmDqMsKXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
