apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:pOmmn/ioTxIV+5nmgwa1yK/ZoP0=,iv:zpyh2VpPfn3SrKUy0hn8LoisXWHQSJkMs7OQtgTVhl0=,tag:HoFLQCcI4ltrbMZ5fruNLQ==,type:str]
    api-key: ENC[AES256_GCM,data:SXTLIr17o3XDCT0DXaPKeOWt79EYHX3opCs8ZHl8UfTxeDiOXQ==,iv:6Lyh0C854RpeUrbvH04JWVBWiA9qdCHPgsmzQ++Hdn0=,tag:pXZ4Krrycy1ec6Phiy9Taw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1japzvh40ygfy2vfdxznvledx3ysna4xkwe4hs4mldf8cg926asrqnackfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UzRFVkR0d2pvOE54RTV1
            ZGRtWVFXTkdxSndBdkVON0RLK1BlaDVSS0JjCndDcWxsRzVEeURiZnpJc2dwb2dC
            U1RMa25CZ09DQjhock1NOWRnOUhiSkEKLS0tIEQydEt4WklXUmI0S2dDTUpMS1B2
            aUI3czlJdmlmYVBtKzJJd2lMZEkyaUUKB+IIxCKlatxiT1Oxhnhqt0I+nf4Q8gst
            dndOU+B4T4sctTcPjjnsffpXGLXhrv5pz89/JUcgr0usrq4LUYmoFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T11:40:10Z"
    mac: ENC[AES256_GCM,data:iaoSygI3Vb7Ps7/kPAuBYtMnS5jciZ0bZ0Xl6I4AnBTnCyuczBXkqH6E3YdU5Qy8qGLi6n6Jifg7grt/r/Ll90QImmeL2j+bNs6oUnSPtliUpbENV5rYpX86VMdHrKEo/Zi4WlHx4rbk1D/ZvPuhh/RU69pU6UgTHr7TTR0hNjg=,iv:7a60aEkjaFxKQkRwtoVeIxNAg+2f+leMKTCwG4CjA9c=,tag:e7b1F1RZsbVkZ7D3oklm5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
