---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "10.24.1.75"
  METALLB_LB_RANGE: "10.24.1.80-10.24.1.90"
  METALLB_K8S_GATEWAY_ADDR: "10.24.1.81"
  METALLB_INGRESS_ADDR: "10.24.1.82"
