apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9HhR069MYGngDA==,iv:La0qFcVh0aD0Optac3j5gUGErYzzKiMTNgvF57kp2iI=,tag:5J/zW2z0BcKMecoisoqyFw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:olmQ3O4Ay5u3KfY5pJkVYcbFqjU=,iv:VkntIWGgNw8C+vVN9HdcSCtJOMXpB+t9mne0v8skDmM=,tag:RjsUXlTolJ8j2J4/ELLkIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1te0jn0p5q6qqu4z7s5nuy0v0zf79zdeur33aq58f53kh6lxjqf4qza4x8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybFd0VzNsZU8weW16d1ZM
            ekJtQjlESEJhY1VxdGVzZ2xiSWJiUk1ZMkVNCnBYNDBHNkd5MmNablBBREpHV1cx
            WTd0T1VKWUthMS9LRExFbWZVeGlVbXMKLS0tIElwdnRmLzRBSkFFMTRGRkRPYmNW
            a05CNXJNcHZlUUlNLzB6MTN2WTFTTVEKs4HOW525clDavImVx1FGQbLBFUlUnkG/
            6kjFn3tRQ7Mc/bQnafiKPAgkSv/g7kzPtmKNRasrIfVCes4URxprBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T09:49:08Z"
    mac: ENC[AES256_GCM,data:r8G7MmxbL2fx6AT2wBLLis7mIHjCUwEmmPX8kh0rS6de19ArQK0Y/90gD+UcTQ1sjK/llKzXiHtzz9TI+89pVPdNajdgfEp/2GHe1QfM3ThRRGxScA78bodCG99WQaAzxzYDeso8yhVhRm8vOHf/IqKe/Bzx/qtv/Az5j7O7Bqo=,iv:yFyimNWlVfPE/UvLr7diPKxlDxeGeiAd4UvYhy85zLA=,tag:uADX/3Q4iw8i6dtmZbtYKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
