---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "10.24.1.198"
  METALLB_LB_RANGE: "10.24.1.160-10.24.1.170"
  METALLB_K8S_GATEWAY_ADDR: "10.24.1.160"
  METALLB_INGRESS_ADDR: "10.24.1.165"
